In [1]:
import numpy as np
import pandas as pd

In [7]:
titanic_train=pd.read_table("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv")
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
151      0            113776  66.6000    C2        S  
152      0        A.5. 11206   8.0500   NaN        S  
153      2          A/5. 851  14.5000   NaN        S  
154      0         Fa 265302   7.3125   NaN        S  
155      1          PC 17597  61.3792   NaN        C  

[156 rows x 12 columns]

In [8]:
titanic_train.tail(10)

PassengerId  Survived  Pclass  \
146          147         1       3   
147          148         0       3   
148          149         0       2   
149          150         0       2   
150          151         0       2   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                             Name     Sex   Age  SibSp  Parch  \
146  Andersson, Mr. August Edvard ("Wennerstrom")    male  27.0      0      0   
147              Ford, Miss. Robina Maggie "Ruby"  female   9.0      2      2   
148      Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5      0      2   
149             Byles, Rev. Thomas Roussel Davids    male  42.0      0      0   
150                    Bateman, Rev. Robert James    male  51.0      0      0   
151             Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1      0   
152                              Meo, Mr. Alfonzo    male  55.5      0      0   
153               van Billiard, Mr. Austin Blyler    male  40.5      0      2   
154                         Olsen, Mr. Ole Martin    male   NaN      0      0   
155                   Williams, Mr. Charles Duane    male  51.0      0      1   

          Ticket     Fare Cabin Embarked  
146       350043   7.7958   NaN        S  
147   W./C. 6608  34.3750   NaN        S  
148       230080  26.0000    F2        S  
149       244310  13.0000   NaN        S  
150  S.O.P. 1166  12.5250   NaN        S  
151       113776  66.6000    C2        S  
152   A.5. 11206   8.0500   NaN        S  
153     A/5. 851  14.5000   NaN        S  
154    Fa 265302   7.3125   NaN        S  
155     PC 17597  61.3792   NaN        C

In [9]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [11]:
titanic_train.dtypes=="object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [13]:
a=titanic_train.dtypes[titanic_train.dtypes=="object"]
a

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [16]:
b=a.index
b

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [18]:
titanic_train[b].describe()

Name   Sex  Ticket Cabin  \
count                                                 156   156     156    31   
unique                                                156     2     145    28   
top     Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  male  113803  C123   
freq                                                    1   100       2     2   

       Embarked  
count       155  
unique        3  
top           S  
freq        110

In [19]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [29]:
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
151      0            113776  66.6000    C2        S  
152      0        A.5. 11206   8.0500   NaN        S  
153      2          A/5. 851  14.5000   NaN        S  
154      0         Fa 265302   7.3125   NaN        S  
155      1          PC 17597  61.3792   NaN        C  

[156 rows x 12 columns]

In [21]:
titanic_train[["PassengerId","Survived"]]

PassengerId  Survived
0              1         0
1              2         1
2              3         1
3              4         1
4              5         0
..           ...       ...
151          152         1
152          153         0
153          154         0
154          155         0
155          156         0

[156 rows x 2 columns]

In [33]:
sorted(titanic_train["Name"])[1:10]

['Allen, Mr. William Henry',
 'Andersson, Miss. Ellis Anna Maria',
 'Andersson, Miss. Erna Alexandra',
 'Andersson, Mr. Anders Johan',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andreasson, Mr. Paul Edvin',
 'Andrew, Mr. Edgardo Samuel',
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)']

In [36]:
titanic_train["cabi_1"]="sdffs"
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   sudh cabi_1  
0      0         A/5 21171   7.2500   NaN        S  sdffs  sdffs  
1      0          PC 17599  71.2833   C85        C  sdffs  sdffs  
2      0  STON/O2. 3101282   7.9250   NaN        S  sdffs  sdffs  
3      0            113803  53.1000  C123        S  sdffs  sdffs  
4      0            373450   8.0500   NaN        S  sdffs  sdffs

In [37]:
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked   sudh cabi_1  
0        0         A/5 21171   7.2500   NaN        S  sdffs  sdffs  
1        0          PC 17599  71.2833   C85        C  sdffs  sdffs  
2        0  STON/O2. 3101282   7.9250   NaN        S  sdffs  sdffs  
3        0            113803  53.1000  C123        S  sdffs  sdffs  
4        0            373450   8.0500   NaN        S  sdffs  sdffs  
..     ...               ...      ...   ...      ...    ...    ...  
151      0            113776  66.6000    C2        S  sdffs  sdffs  
152      0        A.5. 11206   8.0500   NaN        S  sdffs  sdffs  
153      2          A/5. 851  14.5000   NaN        S  sdffs  sdffs  
154      0         Fa 265302   7.3125   NaN        S  sdffs  sdffs  
155      1          PC 17597  61.3792   NaN        C  sdffs  sdffs  

[156 rows x 14 columns]

In [38]:
titanic_train["Pclass"]

0      3
1      1
2      3
3      1
4      3
      ..
151    1
152    3
153    3
154    3
155    1
Name: Pclass, Length: 156, dtype: int64

In [39]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])

In [40]:
new_Pclass

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [41]:
titanic_train["Cabin"].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [42]:
char_cabin = titanic_train["Cabin"].astype(str)

In [43]:
char_cabin

0       nan
1       C85
2       nan
3      C123
4       nan
       ... 
151      C2
152     nan
153     nan
154     nan
155     nan
Name: Cabin, Length: 156, dtype: object

In [44]:
new_Cabin = [cabin[0] for cabin in char_cabin]
new_Cabin 

['n',
 'C',
 'n',
 'C',
 'n',
 'n',
 'E',
 'n',
 'n',
 'n',
 'G',
 'C',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'D',
 'n',
 'A',
 'n',
 'n',
 'n',
 'C',
 'n',
 'n',
 'n',
 'B',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'D',
 'n',
 'B',
 'C',
 'n',
 'n',
 'n',
 'n',
 'n',
 'B',
 'C',
 'n',
 'n',
 'n',
 'F',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'F',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'C',
 'n',
 'n',
 'n',
 'E',
 'n',
 'n',
 'n',
 'A',
 'D',
 'n',
 'n',
 'n',
 'n',
 'D',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'C',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'B',
 'n',
 'n',
 'n',
 'n',
 'E',
 'D',
 'n',
 'n',
 'n',
 'F',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'D',
 'C',
 'n',
 'B',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'F',
 'n',
 'n',
 'C',
 'n',
 'n',
 'n',
 'n']

In [45]:
new_Cabin = pd.Categorical(new_Cabin)

In [46]:
new_Cabin 

[n, C, n, C, n, ..., C, n, n, n, n]
Length: 156
Categories (8, object): [A, B, C, D, E, F, G, n]

In [ ]:
import numpy as np 
char_cabin = titanic_train["Cabin"].astype(str) # Convert data to str

new_Cabin = [cabin[0] for cabin in char_cabin] # Take first letter

new_Cabin = pd.Categorical(new_Cabin)
#new_Cabin
new_Cabin


In [47]:
titanic_train["Cabin"] = new_Cabin
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   sudh cabi_1  
0      0         A/5 21171   7.2500     n        S  sdffs  sdffs  
1      0          PC 17599  71.2833     C        C  sdffs  sdffs  
2      0  STON/O2. 3101282   7.9250     n        S  sdffs  sdffs  
3      0            113803  53.1000     C        S  sdffs  sdffs  
4      0            373450   8.0500     n        S  sdffs  sdffs

In [48]:
titanic_train["Age"].isnull() 

0      False
1      False
2      False
3      False
4      False
       ...  
151    False
152    False
153    False
154     True
155    False
Name: Age, Length: 156, dtype: bool

In [49]:
titanic_train["Age"].isnull() == True

0      False
1      False
2      False
3      False
4      False
       ...  
151    False
152    False
153    False
154     True
155    False
Name: Age, Length: 156, dtype: bool

In [50]:
missing = np.where(titanic_train["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [51]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88], dtype=int64),)

In [52]:
titanic_train.iloc[np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))]

PassengerId  Survived  Pclass                            Name     Sex  \
27           28         0       1  Fortune, Mr. Charles Alexander    male   
88           89         1       1      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare Cabin Embarked   sudh cabi_1  
27  19.0      3      2  19950  263.0     C        S  sdffs  sdffs  
88  23.0      3      2  19950  263.0     C        S  sdffs  sdffs

In [53]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]
titanic_train["Family"]
most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family

(array([59, 71], dtype=int64),)

In [54]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]

most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family
titanic_train.iloc[most_family]

PassengerId  Survived  Pclass                                Name     Sex  \
59           60         0       3  Goodwin, Master. William Frederick    male   
71           72         0       3          Goodwin, Miss. Lillian Amy  female   

     Age  SibSp  Parch   Ticket  Fare Cabin Embarked   sudh cabi_1  Family  
59  11.0      5      2  CA 2144  46.9     n        S  sdffs  sdffs       7  
71  16.0      5      2  CA 2144  46.9     n        S  sdffs  sdffs       7

In [57]:
import numpy as np
import pandas as pd

labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [59]:
arr

array([10, 20, 30])

In [60]:
pd.DataFrame(my_data, index=labels)

0
a  10
b  20
c  30

In [58]:
pd.DataFrame(my_data, index=labels

0
a  10
b  20
c  30

In [61]:
d = {'a':"kjhk",'b':20,'c':30}
d.items
pd.DataFrame(d,index = ['a','b','c'])

a   b   c
a  kjhk  20  30
b  kjhk  20  30
c  kjhk  20  30

In [64]:
ser1 = pd.Series([1,2,3,4],index = [2,4,6,8])
ser2 = pd.Series([1,2,5,4],['CA', 'OR', 'NV', 'AZ'])
ser1

2    1
4    2
6    3
8    4
dtype: int64

In [63]:
ser2

CA    1
OR    2
NV    5
AZ    4
dtype: int64

In [65]:
ser1 = pd.Series([1,2,3,4],['CA', 'OR', 'CO', 'CA'])
ser2 = pd.Series([1,2,5,4],['CA', 'NV', 'AZ','OR'])
ser3 = ser1+ser2
ser3

AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

In [66]:
ser1*ser2

AZ    NaN
CA    1.0
CA    4.0
CO    NaN
NV    NaN
OR    8.0
dtype: float64

In [97]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_labels,column_headings)
#print("\nThe data frame looks like\n",'-'*45, sep='')
df

W         X         Y         Z
A  0.093628  1.240813 -1.097693 -1.908009
B -0.380104 -1.666059 -2.736995  1.522562
C  0.178009 -0.626805 -0.391089  1.743477
D  1.130018  0.897796  0.330866 -1.063049
E -0.125381 -0.945588  2.029544 -1.046358

In [83]:
np.random.seed(101)

In [89]:
matrix_data = rn(5,4)
matrix_data

array([[ 1.60677986, -1.11570997, -1.38537856, -1.32966006],
       [ 0.04145994, -0.4110554 , -0.7713286 ,  0.11047741],
       [-0.80465151,  0.25354804,  0.64914775,  0.35894053],
       [-1.08047146,  0.90239776,  0.16178119,  0.83302932],
       [ 0.97571968, -0.3882387 ,  0.78331605, -0.70895374]])

In [98]:
df

W         X         Y         Z
A  0.093628  1.240813 -1.097693 -1.908009
B -0.380104 -1.666059 -2.736995  1.522562
C  0.178009 -0.626805 -0.391089  1.743477
D  1.130018  0.897796  0.330866 -1.063049
E -0.125381 -0.945588  2.029544 -1.046358

In [99]:
df.iloc[2]

W    0.178009
X   -0.626805
Y   -0.391089
Z    1.743477
Name: C, dtype: float64

In [100]:
df['New'] = df['X']+df['Z']

In [101]:
df

W         X         Y         Z       New
A  0.093628  1.240813 -1.097693 -1.908009 -0.667196
B -0.380104 -1.666059 -2.736995  1.522562 -0.143497
C  0.178009 -0.626805 -0.391089  1.743477  1.116672
D  1.130018  0.897796  0.330866 -1.063049 -0.165253
E -0.125381 -0.945588  2.029544 -1.046358 -1.991947

In [102]:
df1=df.drop('A')
print("\nA row (index) is dropped by using df.drop() method and axis=0\n",'-'*65, sep='')
print(df1)



A row (index) is dropped by using df.drop() method and axis=0
-----------------------------------------------------------------
          W         X         Y         Z       New
B -0.380104 -1.666059 -2.736995  1.522562 -0.143497
C  0.178009 -0.626805 -0.391089  1.743477  1.116672
D  1.130018  0.897796  0.330866 -1.063049 -0.165253
E -0.125381 -0.945588  2.029544 -1.046358 -1.991947


In [104]:
print("\nAn in-place change can be done by making inplace=True in the drop method\n",'-'*75, sep='')
df.drop('New', axis=1, inplace=True)
print(df)


An in-place change can be done by making inplace=True in the drop method
---------------------------------------------------------------------------
          W         X         Y         Z
A  0.093628  1.240813 -1.097693 -1.908009
B -0.380104 -1.666059 -2.736995  1.522562
C  0.178009 -0.626805 -0.391089  1.743477
D  1.130018  0.897796  0.330866 -1.063049
E -0.125381 -0.945588  2.029544 -1.046358


In [106]:
df

W         X         Y         Z
A  0.093628  1.240813 -1.097693 -1.908009
B -0.380104 -1.666059 -2.736995  1.522562
C  0.178009 -0.626805 -0.391089  1.743477
D  1.130018  0.897796  0.330866 -1.063049
E -0.125381 -0.945588  2.029544 -1.046358

In [107]:
df.iloc[3]

W    1.130018
X    0.897796
Y    0.330866
Z   -1.063049
Name: D, dtype: float64

In [112]:
df.loc[["A","B"]]

W         X         Y         Z
A  0.093628  1.240813 -1.097693 -1.908009
B -0.380104 -1.666059 -2.736995  1.522562

In [116]:
matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)


In [117]:
df

W         X         Y         Z
A -0.279510  1.062710  1.752014  0.695547
B  0.153661  0.167638 -0.765930  0.962299
C  0.902826 -0.537909 -1.549671  0.435253
D  1.259904 -0.447898  0.266207  0.412580
E  0.988773  0.513833 -0.928205  0.846904

In [118]:
df.loc[['B','C'],['Y','W']]

Y         W
B -0.765930  0.153661
C -1.549671  0.902826

In [119]:
df.iloc[[1,2,3],[0,1]]

W         X
B  0.153661  0.167638
C  0.902826 -0.537909
D  1.259904 -0.447898

In [120]:
df>0

W      X      Y     Z
A  False   True   True  True
B   True   True  False  True
C   True  False  False  True
D   True  False   True  True
E   True   True  False  True

In [121]:
df.loc[['A','B','C']]>0

W      X      Y     Z
A  False   True   True  True
B   True   True  False  True
C   True  False  False  True

In [122]:
import pandas as pd 
import numpy as np
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']
matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [123]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nA new DataFrame\n",'-'*25, sep='')
print(df)



A new DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [124]:
df[df['Height']>65]

Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160

In [125]:
booldf = df>0
print("\nDataFrame indexed by boolean dataframe\n",'-'*45, sep='')
print(df[booldf])


DataFrame indexed by boolean dataframe
---------------------------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [126]:
booldf1 = df['Height']>65
booldf2 = df['Weight']>145

In [127]:
print("\nRows with Height > 65 inch and Weight >145 lbs\n",'-'*55, sep='')
print(df[(booldf1) & (booldf2)])



Rows with Height > 65 inch and Weight >145 lbs
-------------------------------------------------------
   Age  Height  Weight
B   42      70     148
D   35      68     160


In [128]:
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']


In [129]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe DataFrame\n",'-'*25, sep='')
print(df)



The DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [130]:
print("\nAfter resetting index\n",'-'*35, sep='')
print(df.reset_index())



After resetting index
-----------------------------------
  index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152


In [131]:
print("\nAfter resetting index with 'drop' option TRUE\n",'-'*45, sep='')
print(df.reset_index(drop=True))
"Student Teacher Engineer Doctor Nurse".split()


After resetting index with 'drop' option TRUE
---------------------------------------------
   Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152


['Student', 'Teacher', 'Engineer', 'Doctor', 'Nurse']

In [132]:
print("\nAdding a new column 'Profession'\n",'-'*45, sep='')
df['Profession'] = "Student Teacher Engineer Doctor Nurse".split()
print(df)


Adding a new column 'Profession'
---------------------------------------------
   Age  Height  Weight Profession
A   22      66     140    Student
B   42      70     148    Teacher
C   30      62     125   Engineer
D   35      68     160     Doctor
E   25      62     152      Nurse


In [133]:
print("\nSetting 'Profession' column as index\n",'-'*45, sep='')
print (df.set_index('Profession'))


Setting 'Profession' column as index
---------------------------------------------
            Age  Height  Weight
Profession                     
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152


In [134]:
#multi-indexing
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))


In [136]:
list(zip(outside,inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [137]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
print("\nIndex hierarchy\n",'-'*25, sep='')
print(hier_index)




Index hierarchy
-------------------------
MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )


In [138]:
print(type(hier_index))

<class 'pandas.core.indexes.multi.MultiIndex'>


In [139]:
print("\nCreating DataFrame with multi-index\n",'-'*37, sep='')
#np.random.seed(101)
df1 = pd.DataFrame(data=np.round(rn(6,3)), index= hier_index, columns= ['A','B','C'])
print(df1)


Creating DataFrame with multi-index
-------------------------------------
        A    B    C
G1 1 -0.0  0.0  1.0
   2 -2.0  1.0 -1.0
   3 -1.0  1.0  1.0
G2 1 -1.0 -1.0 -2.0
   2 -1.0  2.0  0.0
   3 -1.0 -0.0 -1.0
